# ITEC 4230 - Satisfeed Project

Notebook Overview: This notebook will keep track of the work done amongst team members to access, clean, and manipulate the dataset provided by Satisfeed clients. The project aims to in the end achieve the display of key metrics and demographic analysis of up to 56 thousand families nourished within Gwinnett county through Satisfeed.

Importing basic necessary libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Loading initial dataset provided by client as dataframe & showing a quick statistical summary

In [ ]:
'''
Make sure to load dataset into files before running this code.
It should be saved under the same name.
'''
dfOriginal = pd.read_csv('/content/sample_data/80169_assistance_report_01-28-2025.csv')
dfOriginal.describe()

,Case Personal income,Household Income,Case Personal expenses,Household Expenses,Pacific Islander,A race/ethnicity not listed here,Vegan,Household Size,Amount,Description,Funding Source,GNAP,Is this a DoorDash Pickup?,TEFAP
count,4459.000000,4459.000000,4459.000000,4459.000000,0.0,0.0,0.0,4459.000000,4459.000000,0.0,0.0,0.0,0.0,0.0
mean,2314.531061,2822.494281,1695.671900,2062.981162,NaN,NaN,NaN,3.034761,1.105181,NaN,NaN,NaN,NaN,NaN
std,8566.018430,11137.532217,7318.351501,8467.493803,NaN,NaN,NaN,1.805829,0.354953,NaN,NaN,NaN,NaN,NaN
min,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN
25%,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN
50%,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,3.000000,1.000000,NaN,NaN,NaN,NaN,NaN
75%,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,4.000000,1.000000,NaN,NaN,NaN,NaN,NaN
max,145600.000000,324000.000000,240000.000000,264000.000000,NaN,NaN,NaN,26.000000,5.000000,NaN,NaN,NaN,NaN,NaN

In [ ]:
#df.dtypes to familiarize ourselves with the columns we are working with
dfOriginal.dtypes

Case #                         object
Entry Date                     object
First Name                     object
Middle Name                    object
Last Name                      object
                               ...
Description                   float64
Funding Source                float64
GNAP                          float64
Is this a DoorDash Pickup?    float64
TEFAP                         float64
Length: 82, dtype: object

Maybe add a small description of the dataset somewhere around here?

In [ ]:
# Setting the index to start at 1
dfOriginal.index = dfOriginal.index + 1

# Showing the first 5 rows
dfOriginal.head()

,Case #,Entry Date,First Name,Middle Name,Last Name,Suffix,Date of Birth,Street Address,Street Apt Number,City,...,Agent Name,Agency Name,Assistance Category,Amount,Unit,Description,Funding Source,GNAP,Is this a DoorDash Pickup?,TEFAP
1,C798529,2/28/2024 13:00,Griselda,NaN,Velasquez,NaN,8/30/1990,1873 Wilson Manor Circle,NaN,Lawrenceville,...,Tim Turner,Satisfeed (S9996),Food: Food Pantry (General),1.0,Boxes/Bags,NaN,NaN,NaN,NaN,NaN
2,C798525,2/28/2024 13:00,Kimberly,NaN,Escobar,NaN,10/25/2000,1873 Wilson Manor Circle,NaN,Lawrenceville,...,Tim Turner,Satisfeed (S9996),Food: Client Choice,1.0,Boxes/Bags,NaN,NaN,NaN,NaN,NaN
3,C801204,2/28/2024 13:00,Karnisha,NaN,Baptist,NaN,5/28/1977,2437 Millbank Ct.,NaN,Lawrenceville,...,Tim Turner,Satisfeed (S9996),Food: Client Choice,1.0,Pounds,NaN,NaN,NaN,NaN,NaN
4,C634208,9/7/2023 11:23,Carmaleta,NaN,Reed,NaN,5/16/1982,2100 Ellison Lakes Dr NW,436,Kennesaw,...,Tim Turner,Satisfeed (S9996),Food: Client Choice,1.0,Pounds,NaN,NaN,NaN,NaN,NaN
5,C793937,2/28/2024 13:00,Maria,NaN,Alves,NaN,1/28/1952,2095 Perrin Springs Dr,NaN,Lawrenceville,...,Tim Turner,Satisfeed (S9996),Food: Client Choice,1.0,Pounds,NaN,NaN,NaN,NaN,NaN

# Cleaning data to show columns we will be using based on the main priorities for the Project

Will not be using columns :

Case Personal Income Sources

Case Personal Expense Sources

Phone Descriptions

Prefers not to answer

A race / ethnicity not listed here

Gluten Free

Vegan

Vegetarian

Jewish - Kosher

Jewish - Non-Kosher

Non-Jewish - Kosher

Diabetic

Nut Allergy

None Apply

Halal

Pork-Free Home

Other.1

Prefer not to answer

Does the household qualify for TEFAP?

Receives Medicare

Door Dash

CSFP Client

Food As Medicine Prescription (Grady Only)

Food As Medicine Neighbor Program (Grady Only)

Food As Medicine Graduate (Grady only)

Other.2

Proxy (Person who can pick up on your behalf)

Agent Name

Agency Name

Description

Funding Source

GNAP

Is this a DoorDash Pickup?

TEFAP

In [ ]:
Df2 = dfOriginal.drop([
    'Case Personal Income Sources',
    'Case Personal Expense Sources',
    'Phone Descriptions',
    'A race/ethnicity not listed here',
    'Gluten Free',
    'Vegan',
    'Vegetarian',
    'Jewish - Kosher',
    'Jewish - Non-Kosher',
    'Non-Jewish - Kosher',
    'Diabetic',
    'Nut Allergy',
    'None Apply',
    'Halal',
    'Pork-Free Home',
    'Other.1',
    'Does the household qualify for TEFAP?',
    'Receives Medicare',
    'Door Dash',
    'CSFP Client',
    'Food As Medicine Prescription (Grady Only)',
    'Food As Medicine Neighbor Program (Grady Only)',
    'Food As Medicine Graduate (Grady only)',
    'Other.2',
    'Prefer not to answer',
    'Proxy (Person who can pick up on your behalf)',
    'Agent Name',
    'Agency Name',
    'Description',
    'Funding Source',
    'GNAP',
    'Is this a DoorDash Pickup?',
    'TEFAP'
], axis=1)

# Showing a quick statistical summary of Df2

Df2.describe()
Df2.head()

,Case #,Entry Date,First Name,Middle Name,Last Name,Suffix,Date of Birth,Street Address,Street Apt Number,City,...,College Student,Not applicable,Unemployed,Veteran,Homeless,Household Size,Assistance Date,Assistance Category,Amount,Unit
1,C798529,2/28/2024 13:00,Griselda,NaN,Velasquez,NaN,8/30/1990,1873 Wilson Manor Circle,NaN,Lawrenceville,...,NaN,NaN,YES,NaN,NaN,1.0,4/20/2024 6:15,Food: Food Pantry (General),1.0,Boxes/Bags
2,C798525,2/28/2024 13:00,Kimberly,NaN,Escobar,NaN,10/25/2000,1873 Wilson Manor Circle,NaN,Lawrenceville,...,NaN,NaN,NaN,NaN,NaN,4.0,4/20/2024 6:15,Food: Client Choice,1.0,Boxes/Bags
3,C801204,2/28/2024 13:00,Karnisha,NaN,Baptist,NaN,5/28/1977,2437 Millbank Ct.,NaN,Lawrenceville,...,NaN,NaN,NaN,NaN,NaN,3.0,4/20/2024 6:15,Food: Client Choice,1.0,Pounds
4,C634208,9/7/2023 11:23,Carmaleta,NaN,Reed,NaN,5/16/1982,2100 Ellison Lakes Dr NW,436,Kennesaw,...,NaN,NaN,NaN,NaN,NaN,3.0,4/20/2024 6:20,Food: Client Choice,1.0,Pounds
5,C793937,2/28/2024 13:00,Maria,NaN,Alves,NaN,1/28/1952,2095 Perrin Springs Dr,NaN,Lawrenceville,...,NaN,NaN,YES,NaN,NaN,2.0,4/20/2024 6:20,Food: Client Choice,1.0,Pounds

In [ ]:
# Filling in the missing values with Unknown or None
Df2.fillna({
    'Case #': 'Unknown',
    'Entry Date': 'Unknown',
    'First Name': 'Unknown',
    'Middle Name': 'Unknown',
    'Last Name': 'Unknown',
    'Suffix': 'Unknown',
    'Date of Birth': 'Unknown',
    'Street Address': 'Unknown',
    'Street Apt Number': 'None',
    'City': 'Unknown',
    'State': 'Unknown',
    'County': 'Unknown',
    'Phone Number': 'Unknown',
    'Email': 'Unknown',
    'Gender': 'Unknown',
    'Education': 'Unknown',
    'Marital status': 'Unknown',
    'Household Size': 'Unknown',
    'Assistance Date': 'Unknown',
    'Assistance Category': 'Unknown',
    'Units': 'Unknown'
    }, inplace=True)

print(Df2)
Df2.head()

        Case #        Entry Date First Name Middle Name    Last Name   Suffix  \
1      C798529   2/28/2024 13:00   Griselda     Unknown    Velasquez  Unknown
2      C798525   2/28/2024 13:00   Kimberly     Unknown      Escobar  Unknown
3      C801204   2/28/2024 13:00   Karnisha     Unknown      Baptist  Unknown
4      C634208    9/7/2023 11:23  Carmaleta     Unknown         Reed  Unknown
5      C793937   2/28/2024 13:00      Maria     Unknown        Alves  Unknown
...        ...               ...        ...         ...          ...      ...
4456   C303638   9/13/2011 13:00   Princess     Unknown       Choloh  Unknown
4457   C798980   2/28/2024 13:00       Deji     Unknown      Adebayo  Unknown
4458   C313907  11/21/2020 15:39      Joyce     Unknown  Mukamugenga  Unknown
4459  C1020408  12/23/2024 21:44   Love Joy     Unknown        Moral  Unknown
4460  C1036661   1/25/2025 13:04       Anne     Unknown       Manalo  Unknown

     Date of Birth            Street Address Street Apt Number           City  \
1        8/30/1990  1873 Wilson Manor Circle              None  Lawrenceville
2       10/25/2000  1873 Wilson Manor Circle              None  Lawrenceville
3        5/28/1977         2437 Millbank Ct.              None  Lawrenceville
4        5/16/1982  2100 Ellison Lakes Dr NW               436       Kennesaw
5        1/28/1952    2095 Perrin Springs Dr              None  Lawrenceville
...            ...                       ...               ...            ...
4456       Unknown     2820 Angel Oak Circle              None         Dacula
4457     6/13/1974   1040 Little Creek Drive              None  Lawrenceville
4458     1/23/1962                   Unknown              None        Unknown
4459      5/9/1989                   Unknown              None        Unknown
4460     1/25/2025                   Unknown              None        grayson

      ... College Student Not applicable Unemployed  Veteran  Homeless  \
1     ...             NaN            NaN        YES      NaN       NaN
2     ...             NaN            NaN        NaN      NaN       NaN
3     ...             NaN            NaN        NaN      NaN       NaN
4     ...             NaN            NaN        NaN      NaN       NaN
5     ...             NaN            NaN        YES      NaN       NaN
...   ...             ...            ...        ...      ...       ...
4456  ...             NaN            NaN        NaN      NaN       NaN
4457  ...             NaN            NaN        NaN      NaN       NaN
4458  ...             NaN            NaN        NaN      NaN       NaN
4459  ...             NaN            NaN        NaN      NaN       NaN
4460  ...             NaN            NaN        NaN      NaN       NaN

      Household Size  Assistance Date          Assistance Category Amount  \
1                1.0   4/20/2024 6:15  Food: Food Pantry (General)    1.0
2                4.0   4/20/2024 6:15          Food: Client Choice    1.0
3                3.0   4/20/2024 6:15          Food: Client Choice    1.0
4                3.0   4/20/2024 6:20          Food: Client Choice    1.0
5                2.0   4/20/2024 6:20          Food: Client Choice    1.0
...              ...              ...                          ...    ...
4456             1.0  1/25/2025 12:50  Food: Food Pantry (General)    1.0
4457             3.0  1/25/2025 12:50  Food: Food Pantry (General)    1.0
4458             1.0  1/25/2025 12:50  Food: Food Pantry (General)    1.0
4459             1.0  1/25/2025 12:55  Food: Food Pantry (General)    1.0
4460             2.0  1/25/2025 13:00  Food: Food Pantry (General)    1.0

            Unit
1     Boxes/Bags
2     Boxes/Bags
3         Pounds
4         Pounds
5         Pounds
...          ...
4456  Boxes/Bags
4457  Boxes/Bags
4458  Boxes/Bags
4459  Boxes/Bags
4460  Boxes/Bags

[4460 rows x 49 columns]

,Case #,Entry Date,First Name,Middle Name,Last Name,Suffix,Date of Birth,Street Address,Street Apt Number,City,...,College Student,Not applicable,Unemployed,Veteran,Homeless,Household Size,Assistance Date,Assistance Category,Amount,Unit
1,C798529,2/28/2024 13:00,Griselda,Unknown,Velasquez,Unknown,8/30/1990,1873 Wilson Manor Circle,None,Lawrenceville,...,NaN,NaN,YES,NaN,NaN,1.0,4/20/2024 6:15,Food: Food Pantry (General),1.0,Boxes/Bags
2,C798525,2/28/2024 13:00,Kimberly,Unknown,Escobar,Unknown,10/25/2000,1873 Wilson Manor Circle,None,Lawrenceville,...,NaN,NaN,NaN,NaN,NaN,4.0,4/20/2024 6:15,Food: Client Choice,1.0,Boxes/Bags
3,C801204,2/28/2024 13:00,Karnisha,Unknown,Baptist,Unknown,5/28/1977,2437 Millbank Ct.,None,Lawrenceville,...,NaN,NaN,NaN,NaN,NaN,3.0,4/20/2024 6:15,Food: Client Choice,1.0,Pounds
4,C634208,9/7/2023 11:23,Carmaleta,Unknown,Reed,Unknown,5/16/1982,2100 Ellison Lakes Dr NW,436,Kennesaw,...,NaN,NaN,NaN,NaN,NaN,3.0,4/20/2024 6:20,Food: Client Choice,1.0,Pounds
5,C793937,2/28/2024 13:00,Maria,Unknown,Alves,Unknown,1/28/1952,2095 Perrin Springs Dr,None,Lawrenceville,...,NaN,NaN,YES,NaN,NaN,2.0,4/20/2024 6:20,Food: Client Choice,1.0,Pounds

In [ ]:
# Filling misiing values with NO
Df2.fillna({
    'Asian': 'NO',
    'Black or African-American': 'NO',
    'Hispanic, Latino, or Spanish Origin': 'NO',
    'Middle Eastern or North African': 'NO',
    'Other': 'NO',
    'Pacific Islander': 'NO',
    'White': 'NO',
    'American Indian': 'NO',
    'Prefers not to answer': 'NO',
    'Undisclosed': 'NO',
    'Multiracial': 'NO',
    'Full time': 'NO',
    'Part time': 'NO',
    'Unemployed-Seeking': 'NO',
    'Unemployed-Not Seeking': 'NO',
    'Disabled': 'NO',
    'Retired': 'NO',
    'College Student': 'NO',
    'Not applicable': 'NO',
    'Unemployed': 'NO',
    'Veteran': 'NO',
    'Homeless': 'NO'
    }, inplace=True)

print(Df2)
Df2.head()

        Case #        Entry Date First Name Middle Name    Last Name   Suffix  \
1      C798529   2/28/2024 13:00   Griselda     Unknown    Velasquez  Unknown
2      C798525   2/28/2024 13:00   Kimberly     Unknown      Escobar  Unknown
3      C801204   2/28/2024 13:00   Karnisha     Unknown      Baptist  Unknown
4      C634208    9/7/2023 11:23  Carmaleta     Unknown         Reed  Unknown
5      C793937   2/28/2024 13:00      Maria     Unknown        Alves  Unknown
...        ...               ...        ...         ...          ...      ...
4456   C303638   9/13/2011 13:00   Princess     Unknown       Choloh  Unknown
4457   C798980   2/28/2024 13:00       Deji     Unknown      Adebayo  Unknown
4458   C313907  11/21/2020 15:39      Joyce     Unknown  Mukamugenga  Unknown
4459  C1020408  12/23/2024 21:44   Love Joy     Unknown        Moral  Unknown
4460  C1036661   1/25/2025 13:04       Anne     Unknown       Manalo  Unknown

     Date of Birth            Street Address Street Apt Number           City  \
1        8/30/1990  1873 Wilson Manor Circle              None  Lawrenceville
2       10/25/2000  1873 Wilson Manor Circle              None  Lawrenceville
3        5/28/1977         2437 Millbank Ct.              None  Lawrenceville
4        5/16/1982  2100 Ellison Lakes Dr NW               436       Kennesaw
5        1/28/1952    2095 Perrin Springs Dr              None  Lawrenceville
...            ...                       ...               ...            ...
4456       Unknown     2820 Angel Oak Circle              None         Dacula
4457     6/13/1974   1040 Little Creek Drive              None  Lawrenceville
4458     1/23/1962                   Unknown              None        Unknown
4459      5/9/1989                   Unknown              None        Unknown
4460     1/25/2025                   Unknown              None        grayson

      ... College Student Not applicable Unemployed  Veteran  Homeless  \
1     ...              NO             NO        YES       NO        NO
2     ...              NO             NO         NO       NO        NO
3     ...              NO             NO         NO       NO        NO
4     ...              NO             NO         NO       NO        NO
5     ...              NO             NO        YES       NO        NO
...   ...             ...            ...        ...      ...       ...
4456  ...              NO             NO         NO       NO        NO
4457  ...              NO             NO         NO       NO        NO
4458  ...              NO             NO         NO       NO        NO
4459  ...              NO             NO         NO       NO        NO
4460  ...              NO             NO         NO       NO        NO

      Household Size  Assistance Date          Assistance Category Amount  \
1                1.0   4/20/2024 6:15  Food: Food Pantry (General)    1.0
2                4.0   4/20/2024 6:15          Food: Client Choice    1.0
3                3.0   4/20/2024 6:15          Food: Client Choice    1.0
4                3.0   4/20/2024 6:20          Food: Client Choice    1.0
5                2.0   4/20/2024 6:20          Food: Client Choice    1.0
...              ...              ...                          ...    ...
4456             1.0  1/25/2025 12:50  Food: Food Pantry (General)    1.0
4457             3.0  1/25/2025 12:50  Food: Food Pantry (General)    1.0
4458             1.0  1/25/2025 12:50  Food: Food Pantry (General)    1.0
4459             1.0  1/25/2025 12:55  Food: Food Pantry (General)    1.0
4460             2.0  1/25/2025 13:00  Food: Food Pantry (General)    1.0

            Unit
1     Boxes/Bags
2     Boxes/Bags
3         Pounds
4         Pounds
5         Pounds
...          ...
4456  Boxes/Bags
4457  Boxes/Bags
4458  Boxes/Bags
4459  Boxes/Bags
4460  Boxes/Bags

[4460 rows x 49 columns]

,Case #,Entry Date,First Name,Middle Name,Last Name,Suffix,Date of Birth,Street Address,Street Apt Number,City,...,College Student,Not applicable,Unemployed,Veteran,Homeless,Household Size,Assistance Date,Assistance Category,Amount,Unit
1,C798529,2/28/2024 13:00,Griselda,Unknown,Velasquez,Unknown,8/30/1990,1873 Wilson Manor Circle,None,Lawrenceville,...,NO,NO,YES,NO,NO,1.0,4/20/2024 6:15,Food: Food Pantry (General),1.0,Boxes/Bags
2,C798525,2/28/2024 13:00,Kimberly,Unknown,Escobar,Unknown,10/25/2000,1873 Wilson Manor Circle,None,Lawrenceville,...,NO,NO,NO,NO,NO,4.0,4/20/2024 6:15,Food: Client Choice,1.0,Boxes/Bags
3,C801204,2/28/2024 13:00,Karnisha,Unknown,Baptist,Unknown,5/28/1977,2437 Millbank Ct.,None,Lawrenceville,...,NO,NO,NO,NO,NO,3.0,4/20/2024 6:15,Food: Client Choice,1.0,Pounds
4,C634208,9/7/2023 11:23,Carmaleta,Unknown,Reed,Unknown,5/16/1982,2100 Ellison Lakes Dr NW,436,Kennesaw,...,NO,NO,NO,NO,NO,3.0,4/20/2024 6:20,Food: Client Choice,1.0,Pounds
5,C793937,2/28/2024 13:00,Maria,Unknown,Alves,Unknown,1/28/1952,2095 Perrin Springs Dr,None,Lawrenceville,...,NO,NO,YES,NO,NO,2.0,4/20/2024 6:20,Food: Client Choice,1.0,Pounds

In [ ]:
# Replacing missing numerical blank values with NaN

Df2[['Zip code', 'Case Personal income',
    'Household Income', 'Case Personal expenses',
    'Household Expenses','Amount']] = Df2[['Zip code', 'Case Personal income',
    'Household Income', 'Case Personal expenses',
    'Household Expenses','Amount']].replace("", np.nan)

print(Df2)
Df2.head()

        Case #        Entry Date First Name Middle Name    Last Name   Suffix  \
1      C798529   2/28/2024 13:00   Griselda     Unknown    Velasquez  Unknown
2      C798525   2/28/2024 13:00   Kimberly     Unknown      Escobar  Unknown
3      C801204   2/28/2024 13:00   Karnisha     Unknown      Baptist  Unknown
4      C634208    9/7/2023 11:23  Carmaleta     Unknown         Reed  Unknown
5      C793937   2/28/2024 13:00      Maria     Unknown        Alves  Unknown
...        ...               ...        ...         ...          ...      ...
4456   C303638   9/13/2011 13:00   Princess     Unknown       Choloh  Unknown
4457   C798980   2/28/2024 13:00       Deji     Unknown      Adebayo  Unknown
4458   C313907  11/21/2020 15:39      Joyce     Unknown  Mukamugenga  Unknown
4459  C1020408  12/23/2024 21:44   Love Joy     Unknown        Moral  Unknown
4460  C1036661   1/25/2025 13:04       Anne     Unknown       Manalo  Unknown

     Date of Birth            Street Address Street Apt Number           City  \
1        8/30/1990  1873 Wilson Manor Circle              None  Lawrenceville
2       10/25/2000  1873 Wilson Manor Circle              None  Lawrenceville
3        5/28/1977         2437 Millbank Ct.              None  Lawrenceville
4        5/16/1982  2100 Ellison Lakes Dr NW               436       Kennesaw
5        1/28/1952    2095 Perrin Springs Dr              None  Lawrenceville
...            ...                       ...               ...            ...
4456       Unknown     2820 Angel Oak Circle              None         Dacula
4457     6/13/1974   1040 Little Creek Drive              None  Lawrenceville
4458     1/23/1962                   Unknown              None        Unknown
4459      5/9/1989                   Unknown              None        Unknown
4460     1/25/2025                   Unknown              None        grayson

      ... College Student Not applicable Unemployed  Veteran  Homeless  \
1     ...              NO             NO        YES       NO        NO
2     ...              NO             NO         NO       NO        NO
3     ...              NO             NO         NO       NO        NO
4     ...              NO             NO         NO       NO        NO
5     ...              NO             NO        YES       NO        NO
...   ...             ...            ...        ...      ...       ...
4456  ...              NO             NO         NO       NO        NO
4457  ...              NO             NO         NO       NO        NO
4458  ...              NO             NO         NO       NO        NO
4459  ...              NO             NO         NO       NO        NO
4460  ...              NO             NO         NO       NO        NO

      Household Size  Assistance Date          Assistance Category Amount  \
1                1.0   4/20/2024 6:15  Food: Food Pantry (General)    1.0
2                4.0   4/20/2024 6:15          Food: Client Choice    1.0
3                3.0   4/20/2024 6:15          Food: Client Choice    1.0
4                3.0   4/20/2024 6:20          Food: Client Choice    1.0
5                2.0   4/20/2024 6:20          Food: Client Choice    1.0
...              ...              ...                          ...    ...
4456             1.0  1/25/2025 12:50  Food: Food Pantry (General)    1.0
4457             3.0  1/25/2025 12:50  Food: Food Pantry (General)    1.0
4458             1.0  1/25/2025 12:50  Food: Food Pantry (General)    1.0
4459             1.0  1/25/2025 12:55  Food: Food Pantry (General)    1.0
4460             2.0  1/25/2025 13:00  Food: Food Pantry (General)    1.0

            Unit
1     Boxes/Bags
2     Boxes/Bags
3         Pounds
4         Pounds
5         Pounds
...          ...
4456  Boxes/Bags
4457  Boxes/Bags
4458  Boxes/Bags
4459  Boxes/Bags
4460  Boxes/Bags

[4460 rows x 49 columns]

,Case #,Entry Date,First Name,Middle Name,Last Name,Suffix,Date of Birth,Street Address,Street Apt Number,City,...,College Student,Not applicable,Unemployed,Veteran,Homeless,Household Size,Assistance Date,Assistance Category,Amount,Unit
1,C798529,2/28/2024 13:00,Griselda,Unknown,Velasquez,Unknown,8/30/1990,1873 Wilson Manor Circle,None,Lawrenceville,...,NO,NO,YES,NO,NO,1.0,4/20/2024 6:15,Food: Food Pantry (General),1.0,Boxes/Bags
2,C798525,2/28/2024 13:00,Kimberly,Unknown,Escobar,Unknown,10/25/2000,1873 Wilson Manor Circle,None,Lawrenceville,...,NO,NO,NO,NO,NO,4.0,4/20/2024 6:15,Food: Client Choice,1.0,Boxes/Bags
3,C801204,2/28/2024 13:00,Karnisha,Unknown,Baptist,Unknown,5/28/1977,2437 Millbank Ct.,None,Lawrenceville,...,NO,NO,NO,NO,NO,3.0,4/20/2024 6:15,Food: Client Choice,1.0,Pounds
4,C634208,9/7/2023 11:23,Carmaleta,Unknown,Reed,Unknown,5/16/1982,2100 Ellison Lakes Dr NW,436,Kennesaw,...,NO,NO,NO,NO,NO,3.0,4/20/2024 6:20,Food: Client Choice,1.0,Pounds
5,C793937,2/28/2024 13:00,Maria,Unknown,Alves,Unknown,1/28/1952,2095 Perrin Springs Dr,None,Lawrenceville,...,NO,NO,YES,NO,NO,2.0,4/20/2024 6:20,Food: Client Choice,1.0,Pounds

In [ ]:
# Clean Dataset
# and saving it as a new csv file

Df2.to_csv('Clean_80169_assistance_report_01-28-2025.csv')

print(Df2)

        Case #        Entry Date First Name Middle Name    Last Name   Suffix  \
1      C798529   2/28/2024 13:00   Griselda     Unknown    Velasquez  Unknown
2      C798525   2/28/2024 13:00   Kimberly     Unknown      Escobar  Unknown
3      C801204   2/28/2024 13:00   Karnisha     Unknown      Baptist  Unknown
4      C634208    9/7/2023 11:23  Carmaleta     Unknown         Reed  Unknown
5      C793937   2/28/2024 13:00      Maria     Unknown        Alves  Unknown
...        ...               ...        ...         ...          ...      ...
4456   C303638   9/13/2011 13:00   Princess     Unknown       Choloh  Unknown
4457   C798980   2/28/2024 13:00       Deji     Unknown      Adebayo  Unknown
4458   C313907  11/21/2020 15:39      Joyce     Unknown  Mukamugenga  Unknown
4459  C1020408  12/23/2024 21:44   Love Joy     Unknown        Moral  Unknown
4460  C1036661   1/25/2025 13:04       Anne     Unknown       Manalo  Unknown

     Date of Birth            Street Address Street Apt Number           City  \
1        8/30/1990  1873 Wilson Manor Circle              None  Lawrenceville
2       10/25/2000  1873 Wilson Manor Circle              None  Lawrenceville
3        5/28/1977         2437 Millbank Ct.              None  Lawrenceville
4        5/16/1982  2100 Ellison Lakes Dr NW               436       Kennesaw
5        1/28/1952    2095 Perrin Springs Dr              None  Lawrenceville
...            ...                       ...               ...            ...
4456       Unknown     2820 Angel Oak Circle              None         Dacula
4457     6/13/1974   1040 Little Creek Drive              None  Lawrenceville
4458     1/23/1962                   Unknown              None        Unknown
4459      5/9/1989                   Unknown              None        Unknown
4460     1/25/2025                   Unknown              None        grayson

      ... College Student Not applicable Unemployed  Veteran  Homeless  \
1     ...              NO             NO        YES       NO        NO
2     ...              NO             NO         NO       NO        NO
3     ...              NO             NO         NO       NO        NO
4     ...              NO             NO         NO       NO        NO
5     ...              NO             NO        YES       NO        NO
...   ...             ...            ...        ...      ...       ...
4456  ...              NO             NO         NO       NO        NO
4457  ...              NO             NO         NO       NO        NO
4458  ...              NO             NO         NO       NO        NO
4459  ...              NO             NO         NO       NO        NO
4460  ...              NO             NO         NO       NO        NO

      Household Size  Assistance Date          Assistance Category Amount  \
1                1.0   4/20/2024 6:15  Food: Food Pantry (General)    1.0
2                4.0   4/20/2024 6:15          Food: Client Choice    1.0
3                3.0   4/20/2024 6:15          Food: Client Choice    1.0
4                3.0   4/20/2024 6:20          Food: Client Choice    1.0
5                2.0   4/20/2024 6:20          Food: Client Choice    1.0
...              ...              ...                          ...    ...
4456             1.0  1/25/2025 12:50  Food: Food Pantry (General)    1.0
4457             3.0  1/25/2025 12:50  Food: Food Pantry (General)    1.0
4458             1.0  1/25/2025 12:50  Food: Food Pantry (General)    1.0
4459             1.0  1/25/2025 12:55  Food: Food Pantry (General)    1.0
4460             2.0  1/25/2025 13:00  Food: Food Pantry (General)    1.0

            Unit
1     Boxes/Bags
2     Boxes/Bags
3         Pounds
4         Pounds
5         Pounds
...          ...
4456  Boxes/Bags
4457  Boxes/Bags
4458  Boxes/Bags
4459  Boxes/Bags
4460  Boxes/Bags

[4460 rows x 49 columns]